### PR TITLE
Add platform-specific ping implementation

### PR DESCRIPTION
**Pull request by JosephRedfern**
Not tested under windows, macOS or cygwin... but should work?

Closes https://github.com/luketimothyjones/pynetcheck/issues/1

### CODE REVIEW

**Comment by JosephRedfern** [comment]
Yeah, I thought that was probably the case -- just didn't want to clutter the global namespace with `TIMING_FOR_LINUX` and `TIMING_FOR_WINDOWS`. Have an alternative solution though, will adjust this PR appropriately.

**Comment by samipfjo** [comment]
No reason to not re-use the variable names. Just add an if/elif/else block at the top that consitionally defines the same global variable names.

**Comment by JosephRedfern** [comment]
@luketimothyjones That's true, I just worry maybe it'd be a bit messy.

See my latest commits for a OO-ified version. Not sure if that's a route you'd like to go down, but the option is there. I've also taken it as an opportunity to add some argument parsing stuff.

**Comment by samipfjo** [comment]
Object oriented was a good call, nice work.

Don't worry about it this time around, but in the future please create separate branches + pull requests for each feature you add. It makes it much easier to do code review if the changes are restricted to one idea.

With that said, oh man, thank you so much for adding argument parsing. That was an deep unspoken desire of mine.

**Comment by chrdavis** [comment]
Ran on windows and hit the below.  Looks like you are missing a "P" in the below which you did have for the non-Windows case

elif sys.platform == 'win32':
            self.percent_lost_re = re.compile(r'(?<percent_lost>\d{1,3})% loss')

Should be

elif sys.platform == 'win32':
            self.percent_lost_re = re.compile(r'(?P<percent_lost>\d{1,3})% loss')


Traceback (most recent call last):
  File "c:\pynetcheck\netcheck.py", line 190, in <module>
    timestamp_format=args.timestamp_format)
  File "c:\pynetcheck\netcheck.py", line 34, in __init__
    self.percent_lost_re = re.compile(r'(?<percent_lost>\d{1,3})% loss')
  File "C:\Python37\lib\re.py", line 234, in compile
    return _compile(pattern, flags)
  File "C:\Python37\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Python37\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Python37\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Python37\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "C:\Python37\lib\sre_parse.py", line 731, in _parse
    len(char) + 2)
re.error: unknown extension ?<p at position 1

**Comment by chrdavis** [comment]
I also hit this after fixing the other issues with the regular expression I called out.

Turns out my router was having issues with pings and they were all timing out.  This means we don't get the output line like the below and we get an error accessing the results of the re search.  We should check that the search returned a valid object.

Approximate round trip times in milli-seconds:
    Minimum = 11ms, Maximum = 16ms, Average = 13ms

Running pings...Traceback (most recent call last):
  File "c:\pynetcheck\netcheck.py", line 193, in <module>
    pnc.run()
  File "c:\pynetcheck\netcheck.py", line 167, in run
    self.ping_speedtest_save()
  File "c:\pynetcheck\netcheck.py", line 85, in ping_speedtest_save
    percent_lost, min_ms, average_ms, max_ms = self.execute_ping()
  File "c:\pynetcheck\netcheck.py", line 135, in execute_ping
    min_ms = int(round(float(timing_match.group('min'))))
AttributeError: 'NoneType' object has no attribute 'group'

Change to:

        min_ms = 0
        average_ms = 0
        max_ms = 0
        
        if timing_match is not None:
            min_ms = int(round(float(timing_match.group('min')))) 
            average_ms = int(round(float(timing_match.group('avg'))))
            max_ms = int(round(float(timing_match.group('max'))))

**Comment by JosephRedfern** [comment]
@luketimothyjones You're totally right, apologies -- refactored to try and reduce any message caused by the cross-platform stuff but it did belong in a PR really.

@chrdavis Thanks for noticing that -- silly omission (caused by lack of a windows box to test on). I'll open an issue to create some unit tests to test parsing, would be good to get some sample output from different OS's under different conditions so we be sure that things like that don't happen again. 

I think maybe that second problem belongs in a different issue -- setting min/avg/max to 0 sort of masks the fact that an error occurred, we might want an alternative way (like a an additional column for storing errors?).

**Comment by samipfjo** [comment]
Confirmed working on Windows 10 and Ubuntu 16.04 LTS

**Comment by samipfjo** [comment]
Whoops. Close != merge, lol
